'use client';

import { useEffect, useState, type ReactNode } from 'react';
import { useSearchParams } from 'next/navigation';
import type { QuoteDetailResponse } from '@unodigit/ba-bot-contract';
import GradientMesh from '@/components/GradientMesh';

/** Baked in at build time — the site is a static export, so there is no
 * runtime config. Matches the discipline in useBaBot.ts: when the origin is
 * absent, this page cannot verify anything, so it fails to the same "not
 * valid" state rather than pointing at a dead endpoint. */
const BOT_API = process.env.NEXT_PUBLIC_BA_BOT_URL;

// ---------------------------------------------------------------------------
// A minimal, safe renderer for the exact subset of Markdown our own Worker
// emits (apps/ba-bot-api/src/render/quote.ts): h1-h3 headings, **bold**,
// _italic_, unordered lists, GFM-style tables, and horizontal rules. No
// dependency was added — the stored markdown is generated by our own
// renderers, so the constructs it can contain are known and small.
//
// This never touches innerHTML. Every node below is a React element built
// from parsed text, so React escapes all text content automatically — the
// project name and problem statement in a quote are visitor-supplied text
// that flowed through the LLM, and this page treats the whole markdown
// string as untrusted despite being Worker-generated.
// ---------------------------------------------------------------------------

type Align = 'left' | 'right';

type Block =
  | { type: 'heading'; level: 1 | 2 | 3; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'list'; items: string[] }
  | { type: 'table'; header: string[]; aligns: Align[]; rows: string[][] }
  | { type: 'hr' };

function tableCells(line: string): string[] {
  let s = line.trim();
  if (s.startsWith('|')) s = s.slice(1);
  if (s.endsWith('|')) s = s.slice(0, -1);
  return s.split('|').map((c) => c.trim());
}

function isSeparatorRow(cells: string[]): boolean {
  return cells.length > 0 && cells.every((c) => /^:?-+:?$/.test(c.trim()));
}

function cellAlign(cell: string): Align {
  return cell.trim().endsWith(':') ? 'right' : 'left';
}

function parseBlocks(source: string): Block[] {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const blocks: Block[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.trim() === '') {
      i++;
      continue;
    }

    const heading = /^(#{1,3})\s+(.*)$/.exec(line);
    if (heading) {
      blocks.push({ type: 'heading', level: heading[1].length as 1 | 2 | 3, text: heading[2].trim() });
      i++;
      continue;
    }

    if (/^-{3,}$/.test(line.trim())) {
      blocks.push({ type: 'hr' });
      i++;
      continue;
    }

    if (line.trim().startsWith('|')) {
      const next = lines[i + 1] ?? '';
      if (next.trim().startsWith('|') && isSeparatorRow(tableCells(next))) {
        const header = tableCells(line);
        const aligns = tableCells(next).map(cellAlign);
        const rows: string[][] = [];
        let j = i + 2;
        while (j < lines.length && lines[j].trim().startsWith('|')) {
          rows.push(tableCells(lines[j]));
          j++;
        }
        blocks.push({ type: 'table', header, aligns, rows });
        i = j;
        continue;
      }
    }

    if (/^-\s+/.test(line)) {
      const items: string[] = [];
      let j = i;
      while (j < lines.length && /^-\s+/.test(lines[j])) {
        items.push(lines[j].replace(/^-\s+/, ''));
        j++;
      }
      blocks.push({ type: 'list', items });
      i = j;
      continue;
    }

    const paraLines: string[] = [];
    let j = i;
    while (
      j < lines.length &&
      lines[j].trim() !== '' &&
      !/^(#{1,3})\s+/.test(lines[j]) &&
      !lines[j].trim().startsWith('|') &&
      !/^-\s+/.test(lines[j]) &&
      !/^-{3,}$/.test(lines[j].trim())
    ) {
      paraLines.push(lines[j]);
      j++;
    }
    blocks.push({ type: 'paragraph', text: paraLines.join(' ') });
    i = j;
  }

  return blocks;
}

/** Splits on **bold** / _italic_ runs. Every returned segment is either a
 * plain string (a React text node, auto-escaped) or a <strong>/<em> element
 * wrapping a plain string — never raw HTML. */
const INLINE_PATTERN = /(\*\*[^*]+\*\*|_[^_]+_)/g;

function renderInline(text: string, keyPrefix: string): ReactNode[] {
  return text
    .split(INLINE_PATTERN)
    .filter((part) => part.length > 0)
    .map((part, idx) => {
      const key = `${keyPrefix}-${idx}`;
      if (part.startsWith('**') && part.endsWith('**') && part.length >= 4) {
        return <strong key={key}>{part.slice(2, -2)}</strong>;
      }
      if (part.startsWith('_') && part.endsWith('_') && part.length >= 2) {
        return <em key={key}>{part.slice(1, -1)}</em>;
      }
      return part;
    });
}

function QuoteTable({ header, aligns, rows }: { header: string[]; aligns: Align[]; rows: string[][] }) {
  const cellStyle = (i: number, muted: boolean) => ({
    textAlign: (aligns[i] ?? 'left') as Align,
    padding: `var(--space-4) var(--space-5)`,
    borderBottom: '1px solid var(--separator)',
    color: muted ? 'var(--label-secondary)' : 'var(--label)',
    fontSize: 'var(--text-footnote)',
  });

  return (
    <div style={{ overflowX: 'auto' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr>
            {header.map((h, i) => (
              <th key={i} style={{ ...cellStyle(i, false), fontWeight: 'var(--weight-semibold)' }}>
                {renderInline(h, `th-${i}`)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, ri) => (
            <tr key={ri} style={{ background: ri % 2 === 1 ? 'var(--fill-4)' : 'transparent' }}>
              {row.map((cell, ci) => (
                <td key={ci} style={cellStyle(ci, true)}>
                  {renderInline(cell, `td-${ri}-${ci}`)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Markdown({ source }: { source: string }) {
  const blocks = parseBlocks(source);

  return (
    <>
      {blocks.map((block, i) => {
        const key = `b-${i}`;
        switch (block.type) {
          case 'heading': {
            const inline = renderInline(block.text, key);
            if (block.level === 1) {
              return (
                <h1 key={key} className="type-title-1" style={{ color: 'var(--label)' }}>
                  {inline}
                </h1>
              );
            }
            if (block.level === 2) return <h2 key={key}>{inline}</h2>;
            return <h3 key={key}>{inline}</h3>;
          }
          case 'paragraph':
            return <p key={key}>{renderInline(block.text, key)}</p>;
          case 'list':
            return (
              <ul key={key}>
                {block.items.map((item, ii) => (
                  <li key={ii}>{renderInline(item, `${key}-${ii}`)}</li>
                ))}
              </ul>
            );
          case 'table':
            return <QuoteTable key={key} header={block.header} aligns={block.aligns} rows={block.rows} />;
          case 'hr':
            return <hr key={key} />;
          default:
            return null;
        }
      })}
    </>
  );
}

// ---------------------------------------------------------------------------
// Page states
// ---------------------------------------------------------------------------

type Status = 'loading' | 'ready' | 'failed';

/** The ONE failure message for every non-success case: a missing parameter,
 * a bad signature, and an unknown id all render this, identically. The
 * Worker deliberately returns the same 403 for a bad signature and an
 * unknown id so quote ids are not enumerable — showing different copy here
 * would undo that. */
function FailedState() {
  return (
    <div className="flex min-h-[40vh] flex-col items-center justify-center text-center">
      <h1 className="type-title-1" style={{ color: 'var(--label)' }}>
        This link is not valid
      </h1>
      <p className="type-body mt-s5 max-w-md" style={{ color: 'var(--label-secondary)' }}>
        We could not open this quote. Links can expire or be mistyped — if you believe this is a
        mistake, please get in touch and we will send it again.
      </p>
    </div>
  );
}

function LoadingState() {
  return (
    <div className="flex min-h-[40vh] items-center justify-center">
      <p className="type-body" style={{ color: 'var(--label-secondary)' }}>
        Loading your quote…
      </p>
    </div>
  );
}

export default function QuoteClient() {
  const searchParams = useSearchParams();
  const id = searchParams.get('id');
  const sig = searchParams.get('sig');

  const [status, setStatus] = useState<Status>('loading');
  const [markdown, setMarkdown] = useState('');

  useEffect(() => {
    // A missing id or sig is refused locally — never sent to the Worker as an
    // empty or undefined signature. Same failure state as a 403.
    if (!id || !sig || !BOT_API) {
      setStatus('failed');
      return;
    }

    let cancelled = false;
    const controller = new AbortController();

    (async () => {
      try {
        const res = await fetch(
          `${BOT_API}/api/quote/${encodeURIComponent(id)}?sig=${encodeURIComponent(sig)}`,
          { signal: controller.signal },
        );
        if (!res.ok) {
          if (!cancelled) setStatus('failed');
          return;
        }
        const body = (await res.json().catch(() => null)) as QuoteDetailResponse | null;
        if (!body || typeof body.markdown !== 'string') {
          if (!cancelled) setStatus('failed');
          return;
        }
        if (!cancelled) {
          setMarkdown(body.markdown);
          setStatus('ready');
        }
      } catch {
        // Network failure, abort, or a malformed response all collapse into
        // the same state as a 403 — this page never distinguishes reasons.
        if (!cancelled) setStatus('failed');
      }
    })();

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [id, sig]);

  return (
    <section className="relative overflow-hidden pb-s12 pt-32 sm:pt-40">
      <GradientMesh soft={status !== 'ready'} fadeOut={status === 'ready'} />
      <div className="container relative z-[1]">
        {status === 'loading' && <LoadingState />}
        {status === 'failed' && <FailedState />}
        {status === 'ready' && (
          <div className="prose-apple mx-auto">
            <Markdown source={markdown} />
          </div>
        )}
      </div>
    </section>
  );
}
