/**
 * The interview's closing line.
 *
 * WHY THIS EXISTS
 *
 * Every visible reply is generated by the state the conversation is LEAVING.
 * `runTurn` produces the reply under the current addendum, and only then does
 * `step()` decide to advance — so the model writes the final message without
 * knowing it is final. When the graph advances into CONTACT the widget swaps
 * the composer for the contact form (BaBot.tsx), and whatever the model just
 * wrote becomes the last thing the visitor reads, with no way to answer it.
 *
 * Both observed shapes are wrong in the same way:
 *
 *   "Perfect — that's your baseline. To wrap this stage, any third-party
 *    services to integrate?"          <- a question they cannot answer
 *
 *   "Thanks for the clarity — Azure preferred, three-month live date,
 *    80-120k AUD budget. That completes the constraints topic. Moving to the
 *    next topic."                      <- promises a topic that never comes
 *
 * The CONTACT addendum already contains the right words ("tell the client you
 * have everything you need and that the short form below will send their brief
 * and estimate") but it is unreachable: no LLM turn ever runs in CONTACT.
 *
 * Rather than spend a second model call to say one fixed sentence, the closing
 * line is deterministic. The acknowledgement the model wrote is worth keeping —
 * it confirms what was captured — so only the trailing dangler is removed.
 */

/** Appended to every reply that hands over to the form. Deterministic, so the
 *  visitor is never left without an instruction even if the strip below misses
 *  a phrasing. */
export const CONTACT_HANDOFF =
  'That is everything I need — add your details in the short form below and I will send your brief and indicative estimate.'

/**
 * Trailing sentences that promise a continuation the visitor will never get.
 *
 * Deliberately matched only at the END of the reply: "next" appearing mid-reply
 * ("the next release", "what happens next for your team") is ordinary content
 * and must survive. Anchoring to the last sentence is what makes a keyword list
 * safe enough to use here.
 */
const CONTINUATION = /\b(next topic|next,|next up|next we|moving on|move on|moving to|next stage|following topic|let us continue|let's continue)\b/i

/** Splits into sentences, keeping terminators. A reply with no terminator at
 *  all comes back as a single chunk, which is the correct degenerate case. */
function sentences(reply: string): string[] {
  return reply.match(/[^.!?]+[.!?]*/g) ?? []
}

/**
 * The reply the visitor should see when this turn hands over to the form.
 *
 * Strips trailing questions and trailing continuation promises, then appends
 * the fixed hand-off. If stripping removes everything — the whole reply was a
 * question — the hand-off stands alone, which still reads correctly.
 */
export function contactHandoffReply(reply: string): string {
  const parts = sentences(reply)

  while (parts.length > 0) {
    const last = parts[parts.length - 1]!.trim()
    if (last.endsWith('?') || CONTINUATION.test(last)) {
      parts.pop()
      continue
    }
    break
  }

  const kept = parts.join('').trim()
  return kept ? `${kept} ${CONTACT_HANDOFF}` : CONTACT_HANDOFF
}
